select *from EMPLOYEES;
select *from DEPARTMENTS;

select FIRST_NAME,LAST_NAME,DEPARTMENT_NAME
from EMPLOYEES e left join DEPARTMENTS d
on e.DEPARTMENT_ID = d.DEPARTMENT_ID;


SELECT CUSTOMER_ID,FIRST_NAME,LAST_NAME,CUSTOMER.address_id,ADDRESS.address_id address, PHONE
from customer left outer join ADDRESS
on customer.ADDRESS_ID=ADDRESS.ADDRESS_ID
where ADDRESS.ADDRESS_ID is null;


SELECT * FROM CUSTOMER FULL OUTER JOIN ADDRESS
ON CUSTOMER.ADDRESS_ID = ADDRESS.ADDRESS_ID
WHERE CUSTOMER.ADDRESS_ID IS NULL OR
      ADDRESS.ADDRESS_ID IS NULL;